"""Builds BCheck DSL from templates based on vuln class and user description."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from urllib.parse import urlparse

from .templates import KEYWORD_MAP, SUPPORTED_CLASSES, TEMPLATES
from .validator import validate


class BCheckScript:
    def __init__(
        self,
        vuln_class: str,
        name: str,
        filename: str,
        dsl_content: str,
        valid: bool,
        warnings: list[str],
    ):
        self.vuln_class = vuln_class
        self.name = name
        self.filename = filename
        self.dsl_content = dsl_content
        self.valid = valid
        self.warnings = warnings

    def to_dict(self) -> dict:
        return {
            "vuln_class": self.vuln_class,
            "name": self.name,
            "filename": self.filename,
            "dsl_content": self.dsl_content,
            "valid": self.valid,
            "warnings": self.warnings,
        }


def resolve_vuln_classes(vuln_classes: list[str], description: str) -> list[str]:
    """Resolve requested vuln classes to known template keys."""
    resolved: list[str] = []

    for cls in vuln_classes:
        cls_lower = cls.lower().replace("-", "_").replace(" ", "_")
        if cls_lower in TEMPLATES:
            resolved.append(cls_lower)
            continue
        # Try keyword map
        for kw, mapped in KEYWORD_MAP.items():
            if kw in cls_lower:
                if mapped not in resolved:
                    resolved.append(mapped)
                break

    # If nothing resolved, fall back to keyword matching against description
    if not resolved:
        desc_lower = description.lower()
        for kw, mapped in KEYWORD_MAP.items():
            if kw in desc_lower and mapped not in resolved:
                resolved.append(mapped)

    return resolved or ["sqli"]  # default to sqli if truly nothing matched


def _safe_filename(vuln_class: str, target_url: str) -> str:
    """Generate a safe, unique .bcheck filename."""
    try:
        hostname = urlparse(target_url).hostname or "target"
    except Exception:
        hostname = "target"
    hostname = re.sub(r"[^a-zA-Z0-9_-]", "_", hostname)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    return f"{vuln_class}_{hostname}_{ts}.bcheck"


def build(
    description: str,
    target_url: str,
    vuln_classes: list[str],
    author: str = "BCheck-MCP",
) -> list[BCheckScript]:
    """Build BCheckScript objects for each resolved vuln class."""
    resolved = resolve_vuln_classes(vuln_classes, description)
    scripts: list[BCheckScript] = []

    for cls in resolved:
        template = TEMPLATES.get(cls)
        if not template:
            continue

        display_name = f"{cls.upper().replace('_', ' ')} - {_short_target(target_url)}"
        dsl = template.format(
            name=display_name,
            description=description or f"Automated {cls} check generated by BCheck-MCP",
            author=author,
            collaborator_payload="{collaborator_payload}",  # pass through as-is for Burp
        )

        validation_errors = validate(dsl)
        scripts.append(
            BCheckScript(
                vuln_class=cls,
                name=display_name,
                filename=_safe_filename(cls, target_url),
                dsl_content=dsl,
                valid=len(validation_errors) == 0,
                warnings=validation_errors,
            )
        )

    return scripts


def _short_target(url: str) -> str:
    try:
        parsed = urlparse(url)
        return parsed.hostname or url
    except Exception:
        return url
